name: Releases

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          npm i pnpm -g

          pnpm i

          pnpm run build
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: clearurls
          path: dist/*.user.js
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: dist/*.user.js
